### ISSUE TITLE
BlockGrowEvent toggle doesnt work in config AND BlockGrowEvent checks for floating crop in grid incorrectly

### ISSUE THREAD

**Issue by CharGamerYT** [DavidS-Repo/SkyGridx#9] opened 2024-12-16 23:10 UTC
Disabling the BlockGrowEvent check toggle in settings.yml doesn't actually turn it off in game. 

That, and if you place farmland on the same y-level as one of the grid layers, then put a crop on top, that crop will never grow. Despite the actual crop itself being one block above the grid y-level, when the farmland is actually the block that truly is within the grid coordinates.
![2024-12-16_16 08 55](https://github.com/user-attachments/assets/b52a7419-e164-4be4-a835-38f873873945)

**Comment by PreedomCL** [comment] 2024-12-17 00:00
I have also noticed this. I don't think that the y-level of the crop is what is affecting the growth. Rather, I have seen that any crop that doesn't have two non-air blocks beneath it does not grow. I have looked at the source a bit, and I think the problem is that the BlockGrowEvent handler is checking for the block two blocks beneath the crop instead of just 1.

EventControl.java:61
``` java
Block block = event.getBlock();
			Block Blockbelow = block.getRelative(0 , -2, 0);
			if (IS_FLOATING.contains((Blockbelow.getType()))) {
				event.setCancelled(true);
			}
```

**Comment by DavidS-Repo** [comment] 2024-12-17 00:04
> I have also noticed this. I don't think that the y-level of the crop is what is affecting the growth. Rather, I have seen that any crop that doesn't have two non-air blocks beneath it does not grow. I have looked at the source a bit, and I think the problem is that the BlockGrowEvent handler is checking for the block two blocks beneath the crop instead of just 1.
> 
> EventControl.java:61
> 
> ```java
> Block block = event.getBlock();
> 			Block Blockbelow = block.getRelative(0 , -2, 0);
> 			if (IS_FLOATING.contains((Blockbelow.getType()))) {
> 				event.setCancelled(true);
> 			}
> ```

Yes, this seem to be the issue, was doing thing because some crops events trigger differently, like cactus and sugarcane. Going to add an additional check for crops with a different trigger point, this should fix the issue.

```java
private static final EnumSet<Material> FARMLAND_CROPS = EnumSet.of(Material.WHEAT, Material.CARROTS, Material.POTATOES, Material.BEETROOTS, Material.MELON_STEM, Material.PUMPKIN_STEM);

@EventHandler(priority = EventPriority.HIGHEST)
	public void onBlockGrow(BlockGrowEvent event) {
		if (BlockGrowEventToggle) {
			Block block = event.getBlock();
			Material cropType = event.getNewState().getType();
			if (FARMLAND_CROPS.contains(cropType)) {
				Block blockBelow = block.getRelative(0, -1, 0);
				if (blockBelow.getType() != Material.FARMLAND) {
					event.setCancelled(true);
				}
			} else {
				Block blockBelow = block.getRelative(0, -2, 0);
				if (IS_FLOATING.contains(blockBelow.getType())) {
					event.setCancelled(true);
				}
			}
		}
	}
```

**Comment by PreedomCL** [comment] 2024-12-17 00:09
Also I noticed this (presumably) typo, which is probably the issue with the config.

``` java
BlockGrowEventToggle = PluginSettings.isBlockIgniteEvent()
```

**Comment by DavidS-Repo** [comment] 2024-12-17 00:15
> Also I noticed this (presumably) typo, which is probably the issue with the config.
> 
> ```java
> BlockGrowEventToggle = PluginSettings.isBlockIgniteEvent()
> ```

Yea, seems like it, thanks for catching that :)

**Comment by DavidS-Repo** [comment] 2024-12-17 01:33
Should be fixed now! Fixed the typo in the `BlockGrowEventToggle` config and added the `FARMLAND_CROPS` check to make sure crops only grow when they're on farmland and not in grid. Also added a check for Cave Vines in `onBlockSpread` to stop them from growing if they're not attached to a block. Let me know if anything else comes up!

**Closed as completed by DavidS-Repo** 2024-12-17 01:33 UTC
Labels: Bug
